#!/bin/bash
# Script para construir el paquete .deb de Bytefense OS

set -e

PACKAGE_NAME="bytefense-os"
VERSION="1.0.0"
ARCH="amd64"
BUILD_DIR="debian-build"
OUTPUT_DIR="dist"

echo "📦 Construyendo paquete .deb de Bytefense OS v$VERSION"

# Limpiar construcción anterior
echo "🧹 Limpiando construcción anterior..."
rm -rf "$BUILD_DIR" "$OUTPUT_DIR"

# Crear estructura de directorios
echo "📁 Creando estructura de directorios..."
mkdir -p "$BUILD_DIR/DEBIAN"
mkdir -p "$BUILD_DIR/opt/bytefense"
mkdir -p "$BUILD_DIR/etc/systemd/system"
mkdir -p "$BUILD_DIR/usr/share/doc/bytefense-os"
mkdir -p "$OUTPUT_DIR"

# Copiar archivos del proyecto
echo "📋 Copiando archivos del proyecto..."
cp -r bin feeds web docs system "$BUILD_DIR/opt/bytefense/" 2>/dev/null || echo "Algunos archivos no se copiaron"

# Copiar servicios systemd si existen
if [ -d "system" ]; then
    cp system/*.service "$BUILD_DIR/etc/systemd/system/" 2>/dev/null || echo "No se encontraron archivos .service"
fi

# Crear archivo control
echo "⚙️ Creando archivo control..."
cat > "$BUILD_DIR/DEBIAN/control" << EOF
Package: bytefense-os
Version: 1.0.0
Section: security
Priority: optional
Architecture: amd64
Depends: python3, python3-pip, iptables, systemd
Maintainer: Bytefense Team <info@bytefense.com>
Description: Bytefense OS - Sistema de Seguridad Integral
 Bytefense OS es una solución completa de seguridad que incluye:
  - Firewall avanzado con IA
  - Sistema de detección de intrusos (IDS)
  - Monitoreo de red en tiempo real
  - Dashboard web interactivo
  - API REST para integración
EOF

# Crear archivo postinst
cat > "$BUILD_DIR/DEBIAN/postinst" << 'EOF'
#!/bin/bash
set -e
echo "Configurando Bytefense OS..."
exit 0
EOF

# Crear archivo prerm
cat > "$BUILD_DIR/DEBIAN/prerm" << 'EOF'
#!/bin/bash
set -e
echo "Deteniendo servicios de Bytefense OS..."
exit 0
EOF

# Crear archivo postrm
cat > "$BUILD_DIR/DEBIAN/postrm" << 'EOF'
#!/bin/bash
set -e
echo "Limpieza completada"
exit 0
EOF

# Establecer permisos
echo "🔐 Estableciendo permisos..."
chmod 755 "$BUILD_DIR/DEBIAN/postinst"
chmod 755 "$BUILD_DIR/DEBIAN/prerm"
chmod 755 "$BUILD_DIR/DEBIAN/postrm"

# Hacer ejecutables los binarios si existen
if [ -d "$BUILD_DIR/opt/bytefense/bin" ]; then
    chmod +x "$BUILD_DIR/opt/bytefense/bin/"* 2>/dev/null || echo "No se pudieron hacer ejecutables algunos archivos"
fi

# Construir el paquete
echo "🔨 Construyendo paquete .deb..."
DEB_FILE="$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"

# Usar dpkg-deb directamente
if dpkg-deb --build "$BUILD_DIR" "$DEB_FILE"; then
    echo "✅ Paquete .deb construido exitosamente: $DEB_FILE"
    
    # Verificar que el archivo existe
    if [ -f "$DEB_FILE" ]; then
        echo "📦 Archivo: $DEB_FILE"
        echo "📏 Tamaño: $(du -h "$DEB_FILE" | cut -f1)"
        
        # Mostrar información del paquete
        echo "📋 Información del paquete:"
        dpkg-deb --info "$DEB_FILE"
    else
        echo "❌ Error: El archivo .deb no se creó correctamente"
        exit 1
    fi
else
    echo "❌ Error al construir el paquete .deb"
    exit 1
fi

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $DEB_FILE"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstalar:"
echo "   sudo dpkg -r $PACKAGE_NAME"
echo "   sudo dpkg -P $PACKAGE_NAME  # Purgar completamente"
echo ""
echo "🎉 Paquete .deb creado exitosamente:"
echo "📦 Archivo: $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "📏 Tamaño: $(du -h "$OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb" | cut -f1)"

echo ""
echo "🚀 Para instalar:"
echo "   sudo dpkg -i $OUTPUT_DIR/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
echo "   sudo apt-get install -f  # Si hay dependencias faltantes"
echo ""
echo "🗑️ Para desinstal